export const FetchBeersTypes = {
    SET_BEERS: 'SET_BEERS',
    FETCH_BEERS_START: 'FETCH_BEERS_START',
    FETCH_BEERS_SUCCESS: 'FETCH_BEERS_SUCCESS',
    FETCH_BEERS_FAILURE: 'FETCH_BEERS_FAILURE'
}